#!/usr/bin/env python3
"""Scene Studio installer UI — a local, browser-based guided installer.

A small stdlib-only web server that serves the static wizard SPA
(``installer/ui/static``) and drives the EXISTING guided installer. It adds
no install logic of its own:

* every question the CLI wizard asks becomes a form field, and every probe
  the wizard performs read-only is re-implemented here 1:1 (ssh subprocess,
  plain HTTP/TCP) so the UI can show structured results instead of parsed
  text;
* the actual install reuses ``Install-SceneStudio.ps1`` in its unattended
  mode (``-Unattended -Answers <file>``) as a child process. Review, the
  bounded apps.yaml/secrets.yaml mutation, backups, the validated deployers
  (backup/stage/hash/verify/rollback), the optional card deploy, and the
  sanitized support report all remain the wizard's tested code paths — the
  UI only streams their output into a log console.
* the deployment answers are written to a temp file in the wizard's own
  answers schema (confirm_install included) — secrets are NEVER part of it.
  The HA long-lived token and the Hue application key are held in this
  process's memory only (entered in the browser or inherited from the
  environment) and passed to the child installer through environment
  variables, exactly like an interactive wizard session.

Cross-platform by construction: Python 3.9+ stdlib, any browser, ssh, and
pwsh 7 — the same four prerequisites the CLI wizard already requires. No
Windows-only APIs (no registry, no Start-Process, no shell=True; paths via
pathlib; the only OS-specific branch is wrapping ``.cmd`` shims with
cmd.exe on Windows for subprocess).

Security posture (this is a LOCAL single-user server):
* binds to the loopback interface only (default 127.0.0.1);
* every ``/api`` call must carry the one-time session token printed in the
  launch URL (a custom header, which also blocks cross-origin requests from
  other pages via preflight) and the Host header must match the bound
  address (DNS-rebinding guard);
* no CORS headers; static assets carry a restrictive CSP;
* secret values are never echoed by any endpoint, never logged, and are
  scrubbed from captured installer output (defense in depth — the wizard
  never prints them anyway).

Usage::

    python installer/ui/server.py [--port 8765] [--no-browser] [--host 127.0.0.1]
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import secrets as secrets_module
import shutil
import socket
import ssl
import subprocess
import sys
import tempfile
import threading
import time
import urllib.error
import urllib.request
import webbrowser
from collections import deque
from datetime import datetime
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

BUNDLE_ROOT = Path(__file__).resolve().parents[2]
STATIC_DIR = Path(__file__).resolve().parent / "static"

INSTALL_WIZARD_NAME = "Install-SceneStudio.ps1"
PROFILE_TOOL_REL = Path("installer") / "scene-studio-profile.py"
MANIFEST_NAME = "MANIFEST.sha256"
SUPPORT_REPORT_RE = re.compile(r"[^\s\"']*[\\/]scene-studio-support-[^\s\"']*\.zip")

MAX_BODY_BYTES = 256 * 1024
MAX_LOG_LINES = 20000

BLOCK_START_MARKER = "# >>> scene_studio managed block (generated by Install-SceneStudio.ps1) >>>"
BLOCK_END_MARKER = "# <<< scene_studio managed block <<<"

DEFAULT_ANSWERS = {
    "ha_url": "",
    "ssh_host": "",
    "ssh_user": "",
    "ssh_port": 22,
    "appdaemon_config_root": None,
    "addon_root_choice": None,
    "store_root": "/config/scene_studio_store",
    "appdaemon_http_url": None,
    "install_ha_card": True,
    "providers": {
        "ha_light": True,
        "hue": {"enabled": False, "host": None, "bridge_id": None},
        "wled": {"enabled": False, "host": None},
        "hyperhdr": {"enabled": False, "host": None},
    },
}

PROBE_NAMES = (
    "ha_api",
    "ha_auth",
    "ssh",
    "appdaemon_http",
    "appdaemon_root",
    "providers",
    "remote_state",
)


class UiError(Exception):
    """A request-level failure with a user-facing message."""

    def __init__(self, status: int, message: str):
        self.status = status
        self.message = message
        super().__init__(message)


# ---------------------------------------------------------------------------
# small cross-platform process helpers
# ---------------------------------------------------------------------------


def find_tool(name: str) -> str | None:
    return shutil.which(name)


def run_command(argv, *, timeout: float | None = None, input_text: str | None = None, env: dict | None = None):
    """subprocess.run with the one Windows quirk handled: .cmd shims must go
    through cmd.exe when CreateProcess cannot execute them directly."""
    argv = [str(part) for part in argv]
    if sys.platform == "win32" and argv[0].lower().endswith((".cmd", ".bat")):
        argv = ["cmd.exe", "/c", *argv]
    return subprocess.run(
        argv,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
        input=input_text,
        env=env,
    )


def bash_single_quote(value: str) -> str:
    """Escape for embedding inside single quotes in a remote shell command
    (same convention as the PowerShell installers)."""
    return value.replace("'", "'\"'\"'")


def tcp_reachable(host: str, port: int, timeout: float = 4.0) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def insecure_ssl_context() -> ssl.SSLContext:
    context = ssl.create_default_context()
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    return context


def http_probe(url: str, *, headers: dict | None = None, timeout: float = 8.0) -> dict:
    """GET a URL; any HTTP answer (even 401) proves reachability.

    Returns {"ok": bool, "http_status": int|None, "body": dict|None,
    "error": str|None} — connection failures carry ``error``.
    """
    request = urllib.request.Request(url, headers=headers or {})
    try:
        with urllib.request.urlopen(  # noqa: S310 - installer probing user-specified LAN endpoints
            request, timeout=timeout, context=insecure_ssl_context()
        ) as response:
            raw = response.read(65536)
            status = response.status
    except urllib.error.HTTPError as exc:
        return {"ok": True, "http_status": exc.code, "body": None, "error": None}
    except (urllib.error.URLError, OSError, ValueError) as exc:
        return {"ok": False, "http_status": None, "body": None, "error": str(exc)}
    body = None
    try:
        body = json.loads(raw.decode("utf-8", errors="replace"))
    except (json.JSONDecodeError, UnicodeDecodeError):
        pass
    return {"ok": True, "http_status": status, "body": body, "error": None}


# ---------------------------------------------------------------------------
# apps.yaml merge preview — a faithful port of the wizard's deterministic
# text merge (Merge-SceneStudioBlock). PREVIEW ONLY: the wizard performs the
# real write with its own copy of this logic.
# ---------------------------------------------------------------------------


def find_block_range(lines: list[str]) -> tuple[int, int] | None:
    for i, line in enumerate(lines):
        if line == BLOCK_START_MARKER:
            for j in range(i + 1, len(lines)):
                if lines[j] == BLOCK_END_MARKER:
                    return (i, j)
            raise UiError(
                400,
                "apps.yaml contains an unterminated scene_studio managed block; fix it manually on the target.",
            )
    for i, line in enumerate(lines):
        if re.match(r"^scene_studio:\s*$", line):
            end = len(lines) - 1
            for j in range(i + 1, len(lines)):
                if re.match(r"^[A-Za-z0-9_-]+:", lines[j]) or lines[j] == BLOCK_START_MARKER:
                    end = j - 1
                    break
            return (i, end)
    return None


def merge_block_preview(original_text: str, block_text: str) -> str:
    managed = [BLOCK_START_MARKER, *block_text.split("\n"), BLOCK_END_MARKER]
    if not original_text.strip():
        return "\n".join(managed) + "\n"
    lines = original_text.replace("\r\n", "\n").split("\n")
    trailing_newline = bool(lines) and lines[-1] == ""
    if trailing_newline:
        lines = lines[:-1]
    rng = find_block_range(lines)
    if rng is not None:
        before = lines[: rng[0]]
        after = lines[rng[1] + 1 :]
    else:
        before = list(lines)
        while before and before[-1] == "":
            before.pop()
        before = [*before, ""]
        after = []
    text = "\n".join([*before, *managed, *after])
    if trailing_newline or not text.endswith("\n"):
        text += "\n"
    return text


# ---------------------------------------------------------------------------
# remote probes (read-only; the same commands the CLI wizard issues)
# ---------------------------------------------------------------------------


def ssh_probe_command(ssh_path: str, destination: str, port: int, command: str, timeout: float = 20.0):
    argv = [ssh_path]
    if port and port > 0:
        argv += ["-p", str(port)]
    argv += ["-o", "BatchMode=yes", "-o", "ConnectTimeout=10", "-o", "StrictHostKeyChecking=accept-new", destination, command]
    return run_command(argv, timeout=timeout)


def split_host_port(value: str, default_port: int) -> tuple[str, int]:
    match = re.match(r"^\[?([^\]]+)\]?:(\d+)$", value)
    if match:
        return match.group(1), int(match.group(2))
    return value, default_port


class InstallerSession:
    """All mutable state of one local installer UI session."""

    def __init__(self) -> None:
        self.lock = threading.RLock()
        self.token = secrets_module.token_urlsafe(24)
        self.wizard_path = self._locate_wizard()
        self.profile_tool = BUNDLE_ROOT / PROFILE_TOOL_REL
        self.card_dist = BUNDLE_ROOT / "home-assistant" / "scene-studio-card" / "dist" / "scene-studio-card.js"
        self.version = self._read_version()
        self.manifest_present = (BUNDLE_ROOT / MANIFEST_NAME).is_file()

        self.answers: dict = json.loads(json.dumps(DEFAULT_ANSWERS))
        self.ha_token: str | None = None  # memory only, never persisted
        self.hue_key: str | None = None  # memory only, never persisted
        self.probe_results: dict[str, dict] = {}
        self.workstation: dict = {}
        self.workdir: Path | None = None

        # child installer run state
        self.run_lock = threading.Lock()
        self.run_status = "idle"  # idle|running|success|failed
        self.run_returncode: int | None = None
        self.run_lines: deque = deque(maxlen=MAX_LOG_LINES)
        self.run_total = 0
        self.run_started: str | None = None
        self.run_finished: str | None = None
        self.run_answers_path: str | None = None
        self.run_support_report: str | None = None
        self._secrets_for_scrub: list[str] = []

    # -- layout -------------------------------------------------------------

    def _locate_wizard(self) -> Path:
        release_position = BUNDLE_ROOT / INSTALL_WIZARD_NAME
        dev_position = BUNDLE_ROOT / "installer" / INSTALL_WIZARD_NAME
        if release_position.is_file():
            return release_position
        if dev_position.is_file():
            return dev_position
        raise UiError(500, f"{INSTALL_WIZARD_NAME} not found under {BUNDLE_ROOT} — re-extract the full release.")

    def _read_version(self) -> str:
        version_file = BUNDLE_ROOT / "VERSION"
        if version_file.is_file():
            return version_file.read_text(encoding="utf-8").strip() or "dev"
        return "dev"

    @property
    def bundle_mode(self) -> str:
        return "release" if self.manifest_present else "development"

    # -- workstation checks (cheap, cached once) ----------------------------

    def ensure_workstation(self) -> dict:
        with self.lock:
            if self.workstation:
                return self.workstation
            python_version = "{}.{}.{}".format(*sys.version_info[:3])
            ssh_path = find_tool("ssh")
            ssh_version = None
            if ssh_path:
                result = run_command([ssh_path, "-V"], timeout=15)
                combined = (result.stdout + result.stderr).strip().splitlines()
                ssh_version = combined[0].strip() if combined and combined[0].strip() else "present (version not reported)"
            pwsh_path = find_tool("pwsh")
            pwsh_version = None
            if pwsh_path:
                result = run_command([pwsh_path, "-NoProfile", "-Command", "$PSVersionTable.PSVersion.ToString()"], timeout=30)
                if result.returncode == 0:
                    pwsh_version = result.stdout.strip()
            self.workstation = {
                "python": python_version,
                "ssh": ssh_version if ssh_path else None,
                "pwsh": pwsh_version,
            }
            return self.workstation

    # -- answers ------------------------------------------------------------

    def update_answers(self, patch: dict) -> dict:
        with self.lock:
            self._merge_answers(self.answers, patch)
            return self.public_answers()

    def _merge_answers(self, target: dict, patch: dict) -> None:
        for key, value in patch.items():
            if key not in DEFAULT_ANSWERS:
                raise UiError(400, f"unknown answers key: {key}")
            if key == "providers":
                if not isinstance(value, dict):
                    raise UiError(400, "providers: expected an object")
                providers = target["providers"]
                for name, provider_patch in value.items():
                    if name not in providers:
                        raise UiError(400, f"unknown provider: {name}")
                    if name == "ha_light":
                        if not isinstance(provider_patch, bool):
                            raise UiError(400, "providers.ha_light: expected a boolean")
                        providers[name] = bool(provider_patch)
                        continue
                    if not isinstance(provider_patch, dict):
                        raise UiError(400, f"providers.{name}: expected an object")
                    for pkey, pvalue in provider_patch.items():
                        if pkey not in providers[name]:
                            raise UiError(400, f"providers.{name}.{pkey}: unknown key")
                        providers[name][pkey] = pvalue
            elif key == "ssh_port":
                try:
                    target[key] = int(value)
                except (TypeError, ValueError):
                    raise UiError(400, "ssh_port: expected a number") from None
            elif key in ("install_ha_card",):
                target[key] = bool(value)
            elif key in ("appdaemon_config_root", "addon_root_choice", "appdaemon_http_url"):
                target[key] = value if value not in ("", None) else None
            else:
                target[key] = "" if value is None else str(value)

    def public_answers(self) -> dict:
        return json.loads(json.dumps(self.answers))

    def set_secret(self, name: str, value: str | None) -> None:
        with self.lock:
            if name == "ha_token":
                self.ha_token = (value or "").strip() or None
            elif name == "hue_key":
                self.hue_key = (value or "").strip() or None
            else:
                raise UiError(400, f"unknown secret: {name}")

    def effective_ha_token(self) -> str | None:
        # the wizard's precedence: what the user entered, else the environment
        return self.ha_token or os.environ.get("SCENE_STUDIO_HA_TOKEN") or None

    # -- secrets scrubbing --------------------------------------------------

    def _scrub(self, text: str) -> str:
        for value in self._secrets_for_scrub:
            if value:
                text = text.replace(value, "[redacted]")
        return text

    # -- probes ---------------------------------------------------------------

    def run_probes(self, names: list[str]) -> dict[str, dict]:
        if self.run_status == "running":
            raise UiError(409, "An install is running; probes are unavailable until it finishes.")
        results: dict[str, dict] = {}
        with self.lock:
            for name in names:
                if name not in PROBE_NAMES:
                    raise UiError(400, f"unknown probe: {name}")
                handler = getattr(self, f"_probe_{name}")
                try:
                    results[name] = handler()
                except Exception as exc:  # a probe must never crash the UI; it reports, not throws
                    results[name] = {"status": "fail", "detail": f"probe error: {exc}", "data": {}}
                self.probe_results[name] = results[name]
        return results

    def _probe_ha_api(self) -> dict:
        ha_url = (self.answers.get("ha_url") or "").strip().rstrip("/")
        if not ha_url:
            return {"status": "skipped", "detail": "Home Assistant address not entered yet.", "data": {}}
        probe = http_probe(f"{ha_url}/api/")
        if probe["ok"]:
            detail = f"reachable (HTTP {probe['http_status']}, authentication required as expected)"
            return {"status": "ok", "detail": detail, "data": {"http_status": probe["http_status"], "url": ha_url}}
        return {
            "status": "fail",
            "detail": f"Home Assistant is not reachable at {ha_url}: {probe['error']}",
            "data": {"url": ha_url},
        }

    def _probe_ha_auth(self) -> dict:
        ha_url = (self.answers.get("ha_url") or "").strip().rstrip("/")
        if not ha_url:
            return {"status": "skipped", "detail": "Home Assistant address not entered yet.", "data": {}}
        token = self.effective_ha_token()
        if not token:
            return {
                "status": "skipped",
                "detail": "No access token provided yet (paste one in step 2 or set SCENE_STUDIO_HA_TOKEN).",
                "data": {},
            }
        probe = http_probe(
            f"{ha_url}/api/config",
            headers={"Authorization": f"Bearer {token}"},
        )
        if not probe["ok"]:
            return {
                "status": "fail",
                "detail": f"The token was rejected by {ha_url}/api/config: {probe['error']} "
                "Create a fresh long-lived token per https://www.home-assistant.io/docs/authentication/.",
                "data": {},
            }
        if probe["http_status"] != 200:
            return {
                "status": "fail",
                "detail": f"The token was rejected (HTTP {probe['http_status']}). "
                "Create a fresh long-lived token per https://www.home-assistant.io/docs/authentication/.",
                "data": {},
            }
        version = ""
        if isinstance(probe["body"], dict):
            version = str(probe["body"].get("version", ""))
        return {"status": "ok", "detail": f"authenticated; Home Assistant {version}".strip(), "data": {"version": version}}

    def _ssh_destination(self) -> str:
        host = (self.answers.get("ssh_host") or "").strip()
        if not host:
            ha_url = (self.answers.get("ha_url") or "").strip()
            if ha_url:
                try:
                    host = re.match(r"^[a-z]+://([^/:?#]+)", ha_url, re.IGNORECASE).group(1)
                except AttributeError:
                    host = ""
        user = (self.answers.get("ssh_user") or "").strip()
        return f"{user}@{host}" if user else host

    def _probe_ssh(self) -> dict:
        destination = self._ssh_destination()
        if not destination:
            return {"status": "skipped", "detail": "ssh target not entered yet.", "data": {}}
        ssh_path = find_tool("ssh")
        if not ssh_path:
            return {"status": "fail", "detail": "No ssh client found on this computer.", "data": {}}
        port = int(self.answers.get("ssh_port") or 22)
        result = ssh_probe_command(ssh_path, destination, port, "echo ok", timeout=20)
        if result.returncode == 0:
            return {"status": "ok", "detail": f"ssh reachable: {destination} (port {port})", "data": {}}
        return {
            "status": "fail",
            "detail": f"ssh to {destination} failed. Check host/port and that ssh KEY authentication is set up "
            "(passwords cannot be typed by the installer). Try: ssh " + destination + " echo ok",
            "data": {"exit_code": result.returncode},
        }

    def appdaemon_http_url(self) -> str:
        explicit = self.answers.get("appdaemon_http_url")
        if explicit:
            return str(explicit).rstrip("/")
        destination = self._ssh_destination()
        host = destination.split("@")[-1].split(":")[0]
        return f"http://{host}:5050"

    def _probe_appdaemon_http(self) -> dict:
        url = self.appdaemon_http_url()
        if not url or url == "http://:5050":
            return {"status": "skipped", "detail": "ssh target not entered yet; nothing to infer from.", "data": {}}
        match = re.match(r"^[a-z]+://([^/:?#]+)(?::(\d+))?", url, re.IGNORECASE)
        if not match:
            return {"status": "fail", "detail": f"not a valid URL: {url}", "data": {}}
        host = match.group(1)
        port = int(match.group(2) or 0) or (443 if url.startswith("https") else 80)
        if tcp_reachable(host, port):
            return {"status": "ok", "detail": f"{url} reachable (tcp/{port})", "data": {"url": url}}
        return {
            "status": "warn",
            "detail": f"{url} is not reachable from this computer right now. Home Assistant and AppDaemon do NOT "
            "have to share a host — enter the AppDaemon HTTP address manually (AppDaemon serves HTTP on its "
            "dashboard port, default 5050; https://appdaemon.readthedocs.io/en/latest/ADDON.html).",
            "data": {"url": url},
        }

    def _ssh_or_fail(self, command: str, timeout: float = 20.0):
        destination = self._ssh_destination()
        ssh_path = find_tool("ssh")
        if not ssh_path or not destination:
            raise UiError(400, "ssh target is not configured/tested yet.")
        result = ssh_probe_command(ssh_path, destination, int(self.answers.get("ssh_port") or 22), command, timeout=timeout)
        if result.returncode != 0:
            raise UiError(400, f"ssh command failed: {command[:80]}… (fix ssh access and re-test)")
        return result.stdout

    def _probe_appdaemon_root(self) -> dict:
        chosen = self.answers.get("appdaemon_config_root")
        if chosen:
            output = self._ssh_or_fail(f"test -d '{bash_single_quote(str(chosen))}' && echo addon_root=present || echo addon_root=absent")
            if "addon_root=absent" in output:
                return {
                    "status": "fail",
                    "detail": f"AppDaemon config directory '{chosen}' does not exist on the target. "
                    "Find the exact add-on slug under /addon_configs on the HA host.",
                    "data": {"selected": str(chosen)},
                }
            return {"status": "ok", "detail": f"using {chosen}", "data": {"selected": str(chosen), "candidates": [str(chosen)]}}
        # auto-detect under /addon_configs (read-only)
        try:
            names_output = self._ssh_or_fail("ls -1 '/addon_configs'")
        except UiError:
            return {
                "status": "skipped",
                "detail": "Auto-detection unavailable (ssh target not reachable/tested); enter the directory manually.",
                "data": {},
            }
        names = [line.strip() for line in names_output.splitlines() if line.strip()]
        candidates: list[str] = []
        for name in names:
            candidate = f"/addon_configs/{name}"
            q = bash_single_quote(candidate)
            result = ssh_probe_command(
                find_tool("ssh"), self._ssh_destination(), int(self.answers.get("ssh_port") or 22),
                f"test -f '{q}/appdaemon.yaml' || test -d '{q}/apps'", timeout=15,
            )
            if result.returncode == 0:
                candidates.append(candidate)
        choice = self.answers.get("addon_root_choice")
        if choice and 1 <= int(choice) <= len(candidates):
            selected = candidates[int(choice) - 1]
        elif len(candidates) == 1:
            selected = candidates[0]
        else:
            selected = None
        if selected is None and candidates:
            return {
                "status": "warn",
                "detail": "Several AppDaemon installations were found — pick one below.",
                "data": {"candidates": candidates, "selected": None},
            }
        if selected is None:
            return {
                "status": "warn",
                "detail": "No AppDaemon config directory detected under /addon_configs — enter it manually "
                "(e.g. /addon_configs/a0d7b954_appdaemon; https://github.com/hassio-addons/addon-appdaemon).",
                "data": {"candidates": [], "selected": None},
            }
        with self.lock:
            if not self.answers.get("appdaemon_config_root"):
                self.answers["appdaemon_config_root"] = selected
        return {"status": "ok", "detail": f"using {selected}", "data": {"candidates": candidates, "selected": selected}}

    def _probe_providers(self) -> dict:
        providers = self.answers.get("providers") or {}
        data: dict = {}
        errors: list[str] = []
        warnings: list[str] = []
        if providers.get("ha_light"):
            data["ha_light"] = {"status": "ok", "detail": "reads through the AppDaemon plugin; no separate host"}
        hue = providers.get("hue") or {}
        if hue.get("enabled"):
            host, port = split_host_port(str(hue.get("host") or ""), 443)
            if tcp_reachable(host, port):
                entry = {"status": "ok", "detail": f"Hue bridge {host}:{port} reachable"}
                bridge_id = hue.get("bridge_id")
                probe = http_probe(f"https://{host}:{port}/api/config", timeout=8)
                if probe["ok"] and isinstance(probe["body"], dict) and probe["body"].get("bridgeid"):
                    bridge_id = str(probe["body"]["bridgeid"])
                    entry["detail"] += f"; bridge id {bridge_id}"
                else:
                    warnings.append("Hue bridge id not detected (used for first-run fixture adoption; can be set later)")
                entry["bridge_id"] = bridge_id
                data["hue"] = entry
                if bridge_id and bridge_id != hue.get("bridge_id"):
                    with self.lock:
                        self.answers["providers"]["hue"]["bridge_id"] = bridge_id
            else:
                data["hue"] = {"status": "fail", "detail": f"Hue bridge {host}:{port} is not reachable"}
                errors.append(f"Hue bridge {host} is not reachable on tcp/{port}.")
        wled = providers.get("wled") or {}
        if wled.get("enabled"):
            host, port = split_host_port(str(wled.get("host") or ""), 80)
            if tcp_reachable(host, port):
                data["wled"] = {"status": "ok", "detail": f"WLED {host}:{port} reachable"}
            else:
                data["wled"] = {"status": "fail", "detail": f"WLED controller {host}:{port} is not reachable"}
                errors.append(f"WLED controller {host} is not reachable on tcp/{port}.")
        hyperhdr = providers.get("hyperhdr") or {}
        if hyperhdr.get("enabled"):
            host, port = split_host_port(str(hyperhdr.get("host") or ""), 8090)
            if tcp_reachable(host, port):
                data["hyperhdr"] = {"status": "ok", "detail": f"hyperHDR {host}:{port} reachable"}
            else:
                data["hyperhdr"] = {"status": "fail", "detail": f"hyperHDR {host}:{port} is not reachable"}
                errors.append(f"hyperHDR {host} is not reachable on tcp/{port}.")
        enabled_any = any(
            (providers.get("ha_light"), (hue or {}).get("enabled"), (wled or {}).get("enabled"), (hyperhdr or {}).get("enabled"))
        )
        if not enabled_any:
            return {"status": "fail", "detail": "At least one lighting source must be enabled.", "data": data}
        if errors:
            return {"status": "fail", "detail": " ".join(errors), "data": data}
        if warnings:
            return {"status": "warn", "detail": " ".join(warnings), "data": data}
        return {"status": "ok", "detail": "all enabled lighting sources reachable", "data": data}

    def _probe_remote_state(self) -> dict:
        root = self.answers.get("appdaemon_config_root")
        if not root:
            return {"status": "skipped", "detail": "AppDaemon config directory not chosen yet.", "data": {}}
        backend_target = f"{str(root).rstrip('/')}/apps/scene_studio"
        workbench_target = f"{str(root).rstrip('/')}/www/scene_studio"
        command = (
            f"if test -d '{bash_single_quote(backend_target)}'; then echo backend=present; else echo backend=absent; fi; "
            f"if test -d '{bash_single_quote(workbench_target)}'; then echo workbench=present; else echo workbench=absent; fi"
        )
        output = self._ssh_or_fail(command)
        backend_present = "backend=present" in output
        workbench_present = "workbench=present" in output
        install_kind = "upgrade" if (backend_present or workbench_present) else "fresh"
        apps_yaml_present = "a=present" in self._ssh_or_fail(
            f"test -f '{bash_single_quote(str(root).rstrip('/') + '/apps.yaml')}' && echo a=present || echo a=absent"
        )
        secrets_yaml_present = "s=present" in self._ssh_or_fail(
            f"test -f '{bash_single_quote(str(root).rstrip('/') + '/secrets.yaml')}' && echo s=present || echo s=absent"
        )
        runtime_mode = "registry_admin"
        if install_kind == "upgrade":
            try:
                api_output = self._ssh_or_fail(
                    "curl -fsS --max-time 8 -X POST -H 'Content-Type: application/json' "
                    '--data \'{"method":"GET","path":"/status"}\' http://127.0.0.1:5050/api/appdaemon/scene_studio_api',
                    timeout=20,
                )
                envelope = json.loads(api_output.strip().splitlines()[-1])
                mode = str(envelope.get("body", {}).get("runtime", {}).get("mode", ""))
                if mode:
                    runtime_mode = mode
            except (UiError, ValueError, AttributeError, IndexError):
                runtime_mode = "registry_admin"
        detail = {
            "fresh": "FRESH install (Scene Studio not found on the target)",
            "upgrade": "upgrade of the existing install",
        }[install_kind]
        return {
            "status": "ok",
            "detail": detail,
            "data": {
                "backend_present": backend_present,
                "workbench_present": workbench_present,
                "install_kind": install_kind,
                "apps_yaml_present": apps_yaml_present,
                "secrets_yaml_present": secrets_yaml_present,
                "runtime_mode": runtime_mode,
            },
        }

    # -- hue pairing (user-initiated; the browser equivalent of the wizard's
    #    "press the LINK button, then press Enter" prompt) --------------------

    def pair_hue(self, host: str) -> dict:
        host_clean = (host or "").strip()
        if not host_clean:
            raise UiError(400, "Hue bridge address is required.")
        bridge_host, port = split_host_port(host_clean, 443)
        body = json.dumps({"devicetype": "scene_studio", "generatekey": True}).encode("utf-8")
        request = urllib.request.Request(
            f"https://{bridge_host}:{port}/api",
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(  # noqa: S310 - user-directed pairing with the local bridge
                request, timeout=15, context=insecure_ssl_context()
            ) as response:
                payload = json.loads(response.read(65536).decode("utf-8", errors="replace"))
        except (urllib.error.URLError, OSError, json.JSONDecodeError, ValueError) as exc:
            return {"ok": False, "error": f"Pairing failed: {exc}. Press the LINK button on the bridge and try again."}
        first = payload[0] if isinstance(payload, list) and payload else {}
        if first.get("error"):
            return {"ok": False, "error": str(first["error"].get("description", first["error"]))}
        key = str(first.get("success", {}).get("username", ""))
        if not key:
            return {"ok": False, "error": "The bridge did not return an application key."}
        with self.lock:
            self.hue_key = key
            self.answers["providers"]["hue"]["enabled"] = True
            self.answers["providers"]["hue"]["host"] = host_clean
        return {"ok": True, "bridge_host": host_clean}

    # -- plan (review payload) ----------------------------------------------

    def build_profile(self) -> dict:
        """The deployment profile, constructed exactly like the wizard builds
        it from the answers (installer/Install-SceneStudio.ps1 step 6)."""
        answers = self.answers
        ha_url = (answers.get("ha_url") or "").strip().rstrip("/")
        if not ha_url:
            raise UiError(400, "Home Assistant address is required.")
        if not (answers.get("ssh_host") or "").strip():
            raise UiError(400, "ssh target is required.")
        root = answers.get("appdaemon_config_root")
        if not root:
            raise UiError(400, "AppDaemon config directory is required (run detection or enter it).")
        remote = self.probe_results.get("remote_state", {}).get("data", {})
        install_kind = remote.get("install_kind", "fresh")
        runtime_mode = remote.get("runtime_mode", "registry_admin") if install_kind == "upgrade" else "registry_admin"
        hue = answers["providers"]["hue"]
        wled = answers["providers"]["wled"]
        hyperhdr = answers["providers"]["hyperhdr"]
        return {
            "ha_url": ha_url,
            "ha_ssh_host": self._ssh_destination(),
            "appdaemon_config_root": root,
            "store_root": answers.get("store_root") or "/config/scene_studio_store",
            "runtime_mode": runtime_mode,
            "providers": {
                "hue": {
                    "enabled": bool(hue.get("enabled")),
                    "host": hue.get("host") if hue.get("enabled") else None,
                    "application_key_secret": "scene_studio_hue_app_key" if hue.get("enabled") else None,
                    "bridge_id": hue.get("bridge_id") or None,
                },
                "wled": {
                    "enabled": bool(wled.get("enabled")),
                    "hosts": [wled["host"]] if wled.get("enabled") and wled.get("host") else [],
                },
                "ha_light": {
                    "enabled": bool(answers["providers"].get("ha_light")),
                    "ignored_entity_ids": [],
                },
            },
            "integrations": {
                "hyperhdr": {
                    "enabled": bool(hyperhdr.get("enabled")),
                    "host": hyperhdr.get("host") if hyperhdr.get("enabled") else None,
                    "default_policy": "yield",
                }
            },
        }

    def _run_profile_tool(self, subcommand: str, profile_path: Path) -> subprocess.CompletedProcess:
        return run_command([sys.executable, str(self.profile_tool), subcommand, "--profile", str(profile_path)], timeout=60)

    def build_plan(self) -> dict:
        if self.run_status == "running":
            raise UiError(409, "An install is running; the plan is unavailable until it finishes.")
        with self.lock:
            profile = self.build_profile()
            workdir = self._ensure_workdir()
            profile_path = workdir / "scene-studio.profile.json"
            profile_path.write_text(json.dumps(profile, indent=2), encoding="utf-8")

            validation = self._run_profile_tool("validate", profile_path)
            if validation.returncode != 0:
                errors = [line.strip().lstrip("- ").strip() for line in validation.stderr.splitlines() if line.strip().startswith("-")]
                return {"ok": False, "errors": errors or [validation.stderr.strip() or "profile validation failed"]}

            rendered = self._run_profile_tool("render-apps-yaml", profile_path)
            if rendered.returncode != 0:
                return {"ok": False, "errors": [rendered.stderr.strip() or "apps.yaml block rendering failed"]}
            rendered_text = rendered.stdout
            notes_index = rendered_text.find("\nNotes:")
            if notes_index < 0:
                notes_index = len(rendered_text)
            block = rendered_text[:notes_index].strip("\n")
            notes = []
            tail = rendered_text[notes_index:]
            for line in tail.splitlines():
                if line.startswith("- "):
                    notes.append(line[2:].strip())

            remote = self.probe_results.get("remote_state", {}).get("data", {})
            install_kind = remote.get("install_kind", "fresh")
            apps_yaml_present = bool(remote.get("apps_yaml_present"))
            merged_preview = None
            apps_yaml_changed = True
            if apps_yaml_present:
                original = self._read_remote_text(f"{str(profile['appdaemon_config_root']).rstrip('/')}/apps.yaml")
                if original is not None:
                    merged_preview = merge_block_preview(original, block)
                    apps_yaml_changed = merged_preview != original

            hue_enabled = bool(self.answers["providers"]["hue"]["enabled"])
            hue_bridge_id = self.answers["providers"]["hue"].get("bridge_id")
            if hue_enabled and not hue_bridge_id:
                notes.append(
                    "providers.hue.bridge_id is unset: hue discovery works, but first-run fixture.adopt on Hue "
                    "lights needs the bridge hardware id (Hue app > Settings > My Hue bridge)."
                )
            return {
                "ok": True,
                "errors": [],
                "profile": profile,
                "summary": self._plan_summary(profile, install_kind),
                "install_kind": install_kind,
                "runtime_mode": profile["runtime_mode"],
                "apps_yaml_present": apps_yaml_present,
                "apps_yaml_changed": apps_yaml_changed,
                "block": block,
                "merged_preview": merged_preview,
                "notes": notes,
                "hue_secret_entry": hue_enabled,
                "card_dist_present": self.card_dist.is_file(),
            }

    def _plan_summary(self, profile: dict, install_kind: str) -> list[dict]:
        answers = self.answers
        enabled = []
        if answers["providers"].get("ha_light"):
            enabled.append("Home Assistant lights")
        if answers["providers"]["hue"]["enabled"]:
            enabled.append("Hue")
        if answers["providers"]["wled"]["enabled"]:
            enabled.append("WLED")
        if answers["providers"]["hyperhdr"]["enabled"]:
            enabled.append("hyperHDR")
        mode_note = (
            " (provider writes blocked until you deliberately enable them)"
            if profile["runtime_mode"] == "registry_admin"
            else ""
        )
        return [
            {"label": "Home Assistant API", "value": profile["ha_url"]},
            {"label": "AppDaemon (ssh)", "value": f"{self._ssh_destination()} port {answers.get('ssh_port') or 22}"},
            {"label": "Scene Studio HTTP", "value": self.appdaemon_http_url()},
            {"label": "AppDaemon config", "value": profile["appdaemon_config_root"]},
            {"label": "Scene Studio data", "value": profile["store_root"]},
            {"label": "Deployment type", "value": "upgrade of the existing install" if install_kind == "upgrade" else "FRESH install"},
            {"label": "Runtime mode", "value": profile["runtime_mode"] + mode_note},
            {"label": "Lighting sources", "value": ", ".join(enabled) or "none"},
            {"label": "HA dashboard card", "value": "yes — deploys to /config/www/scene-studio-card/ (no dashboard is modified)" if answers.get("install_ha_card") else "no"},
        ]

    def _read_remote_text(self, remote_path: str) -> str | None:
        """Read a remote file over ssh (read-only; same base64 convention as
        the wizard). Returns None when the file does not exist."""
        quoted = bash_single_quote(remote_path)
        probe = self._ssh_or_fail(f"sudo test -f '{quoted}' && echo present || echo absent")
        if "present" not in probe:
            return None
        encoded = self._ssh_or_fail(f"sudo cat '{quoted}' | base64 -w0", timeout=30)
        joined = "".join(encoded.split()).strip()
        if not joined:
            return ""
        return base64.b64decode(joined).decode("utf-8", errors="replace")

    def _ensure_workdir(self) -> Path:
        if self.workdir is None or not self.workdir.exists():
            self.workdir = Path(tempfile.mkdtemp(prefix="scene-studio-ui-"))
        return self.workdir

    # -- apply: run the guided wizard unattended ------------------------------

    def start_apply(self, confirm: str) -> dict:
        if confirm != "INSTALL":
            raise UiError(400, 'Confirmation required: the request body must carry "confirm": "INSTALL".')
        with self.run_lock:
            if self.run_status == "running":
                raise UiError(409, "An install is already running in this session.")
            profile = self.build_profile()
            remote = self.probe_results.get("remote_state", {}).get("data", {})
            if remote.get("install_kind", "fresh") == "fresh" and profile["runtime_mode"] != "registry_admin":
                raise UiError(400, "A fresh install must run in registry_admin mode.")
            answers = self.public_answers()
            answers["confirm_install"] = True
            workdir = self._ensure_workdir()
            answers_path = workdir / "installer-ui-answers.json"
            # the answers schema carries NO secret values by design (policy:
            # secrets live in environment variables only)
            answers_path.write_text(json.dumps(answers, indent=2), encoding="utf-8")
            try:
                answers_path.chmod(0o600)
            except OSError:
                pass

            child_env = dict(os.environ)
            child_env["SCENE_STUDIO_HA_URL"] = profile["ha_url"]
            if self.ha_token:
                child_env["SCENE_STUDIO_HA_TOKEN"] = self.ha_token
            if self.answers["providers"]["hue"]["enabled"] and self.hue_key:
                child_env["SCENE_STUDIO_HUE_APP_KEY"] = self.hue_key
            self._secrets_for_scrub = [v for v in (self.ha_token, self.hue_key) if v]

            pwsh_path = find_tool("pwsh")
            if not pwsh_path:
                raise UiError(
                    400,
                    "PowerShell 7 (pwsh) is required on this computer — install it from https://aka.ms/powershell.",
                )
            argv = [pwsh_path, "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(self.wizard_path), "-Unattended", "-Answers", str(answers_path)]
            ssh_port = int(self.answers.get("ssh_port") or 0)
            if ssh_port > 0:
                argv += ["-SshPort", str(ssh_port)]

            self.run_status = "running"
            self.run_returncode = None
            self.run_lines.clear()
            self.run_total = 0
            self.run_started = datetime.now().strftime("%H:%M:%S")
            self.run_finished = None
            self.run_answers_path = str(answers_path)
            self.run_support_report = None

            process = subprocess.Popen(  # noqa: S603 - fixed argv, no shell
                argv,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding="utf-8",
                errors="replace",
                bufsize=1,
                env=child_env,
                cwd=str(BUNDLE_ROOT),
            )
            threading.Thread(target=self._pump_output, args=(process,), daemon=True).start()
            return {"status": "running"}

    def _pump_output(self, process: subprocess.Popen) -> None:
        assert process.stdout is not None
        support_report = None
        for raw_line in process.stdout:
            text = self._scrub(raw_line.rstrip("\r\n"))
            stamp = datetime.now().strftime("%H:%M:%S")
            with self.run_lock:
                self.run_total += 1
                self.run_lines.append({"n": self.run_total, "t": stamp, "text": text})
                if support_report is None:
                    match = SUPPORT_REPORT_RE.search(text)
                    if match:
                        support_report = match.group(0)
            time.sleep(0)  # yield so the HTTP threads can read promptly
        returncode = process.wait(timeout=60)
        with self.run_lock:
            self.run_returncode = returncode
            self.run_status = "success" if returncode == 0 else "failed"
            self.run_finished = datetime.now().strftime("%H:%M:%S")
            if support_report:
                self.run_support_report = support_report

    def run_snapshot(self, since: int) -> dict:
        with self.run_lock:
            lines = [entry for entry in self.run_lines if entry["n"] > since]
            return {
                "status": self.run_status,
                "returncode": self.run_returncode,
                "total": self.run_total,
                "lines": lines,
                "started": self.run_started,
                "finished": self.run_finished,
                "answers_path": self.run_answers_path,
                "support_report": self.run_support_report,
            }

    def reset(self) -> dict:
        with self.run_lock:
            if self.run_status == "running":
                raise UiError(409, "Cannot reset while an install is running.")
            self.run_status = "idle"
        with self.lock:
            self.answers = json.loads(json.dumps(DEFAULT_ANSWERS))
            self.ha_token = None
            self.hue_key = None
            self.probe_results = {}
            self.workdir = None
        return {"status": "idle"}

    # -- serialized session view ----------------------------------------------

    def public_session(self) -> dict:
        with self.lock:
            env_ha_token = bool(os.environ.get("SCENE_STUDIO_HA_TOKEN"))
            env_hue_key = bool(os.environ.get("SCENE_STUDIO_HUE_APP_KEY"))
            return {
                "version": self.version,
                "bundle_mode": self.bundle_mode,
                "bundle_root": str(BUNDLE_ROOT),
                "wizard": str(self.wizard_path),
                "card_dist_present": self.card_dist.is_file(),
                "manifest_present": self.manifest_present,
                "workstation": self.ensure_workstation(),
                "env_tokens": {"ha_token": env_ha_token, "hue_key": env_hue_key},
                "secrets_entered": {"ha_token": bool(self.ha_token or env_ha_token), "hue_key": bool(self.hue_key)},
                "answers": self.public_answers(),
                "probes": self.probe_results,
                "run": {key: value for key, value in self.run_snapshot(0).items() if key != "lines"},
            }


# ---------------------------------------------------------------------------
# HTTP layer
# ---------------------------------------------------------------------------


class InstallerUiHandler(BaseHTTPRequestHandler):
    server_version = "SceneStudioInstallerUI/1.0"
    session: InstallerSession  # injected via server attribute

    # -- plumbing -------------------------------------------------------------

    def log_message(self, fmt, *args):  # keep the operator console quiet
        return

    def _json(self, status: int, payload) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _error(self, status: int, message: str) -> None:
        self._json(status, {"error": message})

    def _read_json_body(self) -> dict:
        length = int(self.headers.get("Content-Length") or 0)
        if length <= 0:
            return {}
        if length > MAX_BODY_BYTES:
            raise UiError(413, "request body too large")
        raw = self.rfile.read(length)
        try:
            payload = json.loads(raw.decode("utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            raise UiError(400, "request body is not valid JSON") from None
        if not isinstance(payload, dict):
            raise UiError(400, "request body must be a JSON object")
        return payload

    def _guard(self) -> None:
        """Loopback, Host-header, and session-token checks for /api calls."""
        port = self.server.server_address[1]
        allowed_hosts = {f"127.0.0.1:{port}", f"localhost:{port}", f"[::1]:{port}"}
        if self.headers.get("Host", "") not in allowed_hosts:
            raise UiError(403, "unexpected Host header")
        if self.headers.get("X-Scene-Studio-Token") != self.session.token:
            raise UiError(401, "missing or wrong session token (open the URL printed by the server)")

    def _dispatch(self, method: str) -> None:
        path = self.path.split("?", 1)[0]
        try:
            if path.startswith("/api/"):
                self._guard()
                handler = getattr(self, f"api_{method.lower()}_{path[len('/api/'):].replace('/', '_')}", None)
                if handler is None:
                    raise UiError(404, f"unknown API route: {method} {path}")
                handler()
                return
            if method == "GET":
                self._serve_static(path)
                return
            raise UiError(405, "method not allowed")
        except UiError as exc:
            try:
                self._error(exc.status, exc.message)
            except (BrokenPipeError, ConnectionResetError):
                pass
        except (BrokenPipeError, ConnectionResetError):
            pass

    def do_GET(self):  # noqa: N802
        self._dispatch("GET")

    def do_POST(self):  # noqa: N802
        self._dispatch("POST")

    # -- static ---------------------------------------------------------------

    STATIC_FILES = {
        "/": ("index.html", "text/html; charset=utf-8"),
        "/index.html": ("index.html", "text/html; charset=utf-8"),
        "/app.js": ("app.js", "text/javascript; charset=utf-8"),
        "/style.css": ("style.css", "text/css; charset=utf-8"),
    }

    def _serve_static(self, path: str) -> None:
        entry = self.STATIC_FILES.get(path)
        if entry is None:
            self._error(404, "not found")
            return
        filename, content_type = entry
        try:
            body = (STATIC_DIR / filename).read_bytes()
        except OSError:
            self._error(500, f"static file missing: {filename} — the installer UI is incomplete.")
            return
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header(
            "Content-Security-Policy",
            "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'",
        )
        self.end_headers()
        self.wfile.write(body)

    # -- API -------------------------------------------------------------------

    def api_get_session(self) -> None:
        self._json(200, self.session.public_session())

    def api_post_answers(self) -> None:
        if self.session.run_status == "running":
            raise UiError(409, "An install is running; answers are locked until it finishes.")
        patch = self._read_json_body()
        self._json(200, {"answers": self.session.update_answers(patch)})

    def api_post_secrets(self) -> None:
        body = self._read_json_body()
        changed = {}
        for name in ("ha_token", "hue_key"):
            if name in body:
                self.session.set_secret(name, body[name])
                changed[name] = True
        with self.session.lock:
            env_ha = bool(os.environ.get("SCENE_STUDIO_HA_TOKEN"))
            self._json(
                200,
                {"secrets_entered": {"ha_token": bool(self.session.ha_token or env_ha), "hue_key": bool(self.session.hue_key)}},
            )

    def api_post_probe(self) -> None:
        body = self._read_json_body()
        names = body.get("names")
        if not isinstance(names, list) or not names or not all(isinstance(item, str) for item in names):
            raise UiError(400, "expected body {\"names\": [probe, ...]}")
        results = self.session.run_probes(names)
        # probes may refine the answers (e.g. a detected config root is
        # auto-selected); echo them back so the UI stays in sync
        with self.session.lock:
            self._json(200, {"results": results, "answers": self.session.public_answers()})

    def api_post_hue_pair(self) -> None:
        body = self._read_json_body()
        self._json(200, self.session.pair_hue(str(body.get("host") or "")))

    def api_post_plan(self) -> None:
        self._json(200, self.session.build_plan())

    def api_post_apply(self) -> None:
        body = self._read_json_body()
        self._json(200, self.session.start_apply(str(body.get("confirm") or "")))

    def api_get_run(self) -> None:
        query = self.path.split("?", 1)[1] if "?" in self.path else ""
        since = 0
        for part in query.split("&"):
            if part.startswith("since="):
                try:
                    since = int(part[6:])
                except ValueError:
                    since = 0
        self._json(200, self.session.run_snapshot(since))

    def api_post_reset(self) -> None:
        self._json(200, self.session.reset())


class InstallerUiServer(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True

    def __init__(self, address, handler_class, session: InstallerSession):
        super().__init__(address, handler_class)
        self.session = session


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--host", default="127.0.0.1", help="bind address (default: 127.0.0.1 — keep it local)")
    parser.add_argument("--port", type=int, default=8765, help="port (default: 8765; 0 picks a free port)")
    parser.add_argument("--no-browser", action="store_true", help="do not open the browser automatically")
    args = parser.parse_args(argv)

    try:
        session = InstallerSession()
    except UiError as exc:
        print(f"Scene Studio installer UI cannot start: {exc.message}", file=sys.stderr)
        return 1

    host = args.host
    if host not in ("127.0.0.1", "localhost", "::1"):
        print("warning: binding a non-loopback address exposes this installer to your network.", file=sys.stderr)

    try:
        server = InstallerUiServer((host, args.port), InstallerUiHandler, session)
    except OSError as exc:
        print(f"cannot bind {host}:{args.port}: {exc}", file=sys.stderr)
        return 1
    InstallerUiHandler.session = session
    port = server.server_address[1]
    url = f"http://{host}:{port}/?token={session.token}"
    # flush=True: the banner (and the token URL) must reach piped stdout
    # immediately — launchers and tests parse it line by line.
    print("Scene Studio Installer UI", flush=True)
    print(f"  bundle : {BUNDLE_ROOT} ({session.bundle_mode}, v{session.version})", flush=True)
    print(f"  open   : {url}", flush=True)
    print("  this window must stay open; press Ctrl+C to stop the installer UI.", flush=True)
    if not args.no_browser:
        threading.Timer(0.4, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\ninstaller UI stopped.")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
